---
- name: Setup WebServer
  hosts: 172.31.88.244
  become: yes
  tasks:
    - name: Install Apache httpd 
      yum:
         name: httpd
         state: present
      register: output
      tags: 
       - httpd
    - name: Start & Enable HTTPD
      service:
        name: httpd
        state: started
        enabled: yes

    - name: show output file
      debug:
        var: output
      tags: 
       - output
